---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.rb"
exclude_paths:
- "node_modules/"
- ".idea/"
